import { Category } from "models/Category"

const flatList = (list: Array<Category>, separator = ">") => {
	let result: Array<Category> = []

	// Discarding _id's from JSON for now as they can be autogenerated here or will be taken from DB

	list.map((item, index) => {
		if (item.hasOwnProperty("children")) {
			const { name } = item
			result = [
				...result,
				{ _id: (index + 1).toString(), name },
				...flatList(item.children, separator).map((child, cIndex) => ({
					...child,
					_id: (index + 1).toString() + (cIndex + 1).toString(),
					name: `${name} ${separator} ${child.name}`
				}))
			]
		} else {
			result = [...result, { _id: (index + 1).toString(), name: item.name }]
		}
	})

	return result
}

export default flatList
