type User {
	_id: ID!
	name: String!
	email: String!
	avatar: Image
	contact: Float
	username: String
	password: String
	private: Boolean
	ads: [Ad]
	saved: [Ad]
	follows: [User]
	createdAt: String!
	lastOnline: String!
}
